---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update package cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
      failed_when: false

    - name: Install network utilities (Debian/Ubuntu)
      ansible.builtin.apt:
        name:
          - iputils-ping
          - iputils-arping
          - tcpdump
        state: present
      when: ansible_os_family == 'Debian'
      failed_when: false
