---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update apt cache (Debian)
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'
      ignore_errors: true

    - name: Install iputils-ping (Debian)
      apt:
        name: iputils-ping
        state: present
      when: ansible_os_family == 'Debian'
      ignore_errors: true

    - name: Install iputils-arping (Debian)
      apt:
        name: iputils-arping
        state: present
      when: ansible_os_family == 'Debian'
      ignore_errors: true

    - name: Install tcpdump (Debian)
      apt:
        name: tcpdump
        state: present
      when: ansible_os_family == 'Debian'
      ignore_errors: true